alias today='date "+%Y%m%d"'
alias dc='docker container'
alias dcl='docker container ls'
alias dca='docker container ls -a'
alias dcp='docker container cp'
alias dcm='docker container rm'
alias dce='docker container exec'
alias dv='docker volume'
alias dvl='docker volume ls'
alias di='docker image'
alias dil='docker image ls'
alias dia='docker image ls -a'
alias dn='docker network'
alias dnl='docker network ls'
alias sls='s3cmd ls'
alias sg='s3cmd get'

